### Crear un nuevo turno
POST http://localhost:3000/appointments
Content-Type: application/json

{
  "appoinmentDateTime": "2025-07-10T14:00:00Z",
  "offeredServiceId": "d3b07384-d9a7-4d1a-b78c-0123456789ab",
  "client": {
    "name":" Chiara",
    "lastName": "Kordek",
    "phoneNumber": "+54123456789",
    "email": "creenquesoygolfista@gmail.com"
  }
}

###

### Obtener todos los turnos
GET http://localhost:3000/appointments

###

### Obtener todos los turnos según estado
GET http://localhost:3000/appointments?status=pending

###

### Obtener un turno por ID
GET http://localhost:3000/appointments/a1

###

### Obtener turnos del usuario logueado
GET http://localhost:3000/appointments/me

###

### Obtener turnos por día
GET http://localhost:3000/appointments/day?date=2025-07-09

###

### Obtener turnos por semana
GET http://localhost:3000/appointments/week?date=2025-07-03

###

### Obtener turnos por mes
GET http://localhost:3000/appointments/month?date=2025-08-01

###

### Obtener turnos por año
GET http://localhost:3000/appointments/year?date=2025-01-01

###

### Actualizar un turno por ID
PUT http://localhost:3000/appointments/a1
Content-Type: application/json

{
  "appoinmentDateTime": "2025-07-11T16:00:00Z",
  "client" : {
    "name" : "Valentin"
  }
}

###

### Cambiar estado de un turno
PATCH http://localhost:3000/appointments/a1/status
Content-Type: application/json

{
  "status": "CANCELLED"
}

###

### Eliminar un turno
DELETE http://localhost:3000/appointments/a2


### Create a new company
POST http://localhost:3000/companies
Content-Type: application/json

{
  "name": "Kairos Estética",
  "icon": "https://chatgpt.com/c/68750c7a-2c18-800b-8d01-5b3090102cd1.png",
  "location": "Buenos Aires",
  "services": [],
  "availability": [
    {
      "days": [
        {
          "day": "MONDAY",
          "timeSlots": [{ "startTime": "09:00", "endTime": "18:00" }]
        }
      ]
    }
  ],
  "availabilityException": []
}

###

### Get all companies
GET http://localhost:3000/companies

###

### Get company by ID
GET http://localhost:3000/companies/f2bf17ab-9d54-4e12-bd56-c5142cb0761d

###

### Update a company
PUT http://localhost:3000/companies/f2bf17ab-9d54-4e12-bd56-c5142cb0761d
Content-Type: application/json

{
  "location": "Córdoba"
}

###

### Delete a company
DELETE http://localhost:3000/companies/33d8263c-ad58-4fea-8379-b4882ba4fae5

###

### Get all professionals of a company
GET http://localhost:3000/companies/f2bf17ab-9d54-4e12-bd56-c5142cb0761d/professionals

###

### Get a specific professional from a company
GET http://localhost:3000/companies/f2bf17ab-9d54-4e12-bd56-c5142cb0761d/professionals/f41a1257-819b-4029-ab33-68c9fea7b137

###

### Add a professional to a company
POST http://localhost:3000/companies/f2bf17ab-9d54-4e12-bd56-c5142cb0761d/professionals/f41a1257-819b-4029-ab33-68c9fea7b137
Content-Type: application/json

{
  "roles": ["professional"]
}

###

### Remove a professional from a company
DELETE http://localhost:3000/companies/f2bf17ab-9d54-4e12-bd56-c5142cb0761d/professionals/f41a1257-819b-4029-ab33-68c9fea7b137

###

### Get all services of a company
GET http://localhost:3000/companies/f2bf17ab-9d54-4e12-bd56-c5142cb0761d/services

###

### Add a service to a company
POST http://localhost:3000/companies/f2bf17ab-9d54-4e12-bd56-c5142cb0761d/services/s1
###

### Remove a service from a company
DELETE http://localhost:3000/companies/f2bf17ab-9d54-4e12-bd56-c5142cb0761d/services/s1
