### Create a new company
POST http://localhost:3000/companies
Content-Type: application/json

{
  "name": "Kairos Estética",
  "icon": "https://chatgpt.com/c/68750c7a-2c18-800b-8d01-5b3090102cd1.png",
  "location": "Buenos Aires",
  "services": [],
  "availability": [
    {
      "days": [
        {
          "day": "MONDAY",
          "timeSlots": [{ "startTime": "09:00", "endTime": "18:00" }]
        }
      ]
    }
  ],
  "availabilityException": []
}

###

### Get all companies
GET http://localhost:3000/companies

###

### Get company by ID
GET http://localhost:3000/companies/ba7dfcf6-6748-11f0-b676-00ff1d8344ad

###

### Update a company
PUT http://localhost:3000/companies/ba7dfcf6-6748-11f0-b676-00ff1d8344ad
Content-Type: application/json

{
  "location": "Córdoba"
}

###

### Delete a company
DELETE http://localhost:3000/companies/ba7dfcf6-6748-11f0-b676-00ff1d8344ad

###

### Get all professionals from a company (ISSUE)
GET http://localhost:3000/companies/ba7dfa80-6748-11f0-b676-00ff1d8344ad/professionals

###

### Get all services of a company  (ISSUE) 
GET http://localhost:3000/companies/f2bf17ab-9d54-4e12-bd56-c5142cb0761d/services