### Obtener información de un profesional por ID
GET http://localhost:3000/professionals/ba84710c-6748-11f0-b676-00ff1d8344ad

### Actualizar perfil del profesional (patch)
PATCH http://localhost:3000/professionals/ba84710c-6748-11f0-b676-00ff1d8344ad/profile
Content-Type: application/json

{
  "firstName": "Juan Pérez",
  "phoneNumber": "430123456789",
  "email": "juan@example.com"
}

### Obtener información de un profesional por ID de usuario
GET http://localhost:3000/professionals/user/ba80ff81-6748-11f0-b676-00ff1d8344ad
