@baseUrl = http://localhost:3000

### 🔹 Crear un nuevo servicio
POST {{baseUrl}}/services
Content-Type: application/json

{
  "name": "Masaje terapéutico test v1",
  "description": "Masaje profundo para aliviar tensiones musculares",
  "suggestedPrice": 3500,
  "suggestedDuration": 60,
  "companyId": "ba7dfa80-6748-11f0-b676-00ff1d8344ad"
}
###

### 🔹 Obtener todos los servicios
GET {{baseUrl}}/services

###

### 🔹 Obtener servicio por ID
GET {{baseUrl}}/services/ba89b6b4-6748-11f0-b676-00ff1d8344ad

###

### 🔹 Actualizar servicio
PUT {{baseUrl}}/services/ba89b6b4-6748-11f0-b676-00ff1d8344ad
Content-Type: application/json

{
  "name": "Masaje descontracturante",
  "description": "Masaje suave con enfoque en áreas tensas",
  "suggestedPrice": 4000,
  "suggestedDuration": 45
}

###

### 🔹 Eliminar servicio
DELETE {{baseUrl}}/services/72228ec0-3762-4249-8893-fa54bcddd9b6