### Crear un nuevo staff member
POST http://localhost:3000/staff-members
Content-Type: application/json

{
  "companyId": 1,
  "professionalId": 1,
  "roleId": 1
}

### Eliminar staff member por ID
DELETE http://localhost:3000/staff-members/1

### Obtener staff members de una compañía
GET http://localhost:3000/staff-members/company/1

### Actualizar rol de un staff member
PATCH http://localhost:3000/staff-members/1/role
Content-Type: application/json

{
  "roleId": 2
}
